services:

  postgres:
    image: postgres:17
    container_name: dev_onboard_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: onboard
    volumes:
      - pgdata:/var/lib/postgresql/data        # persistance des données
      - ./db/init:/docker-entrypoint-initdb.d # place tes scripts SQL init/seed ici
    ports:
      - "5432:5432"                           # exposé pour IDE/psql sur l'hôte
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: dev_onboard_grafana
    ports:
      - "3000:3000"                            # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dev_onboard_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"                              # UI pgAdmin accessible sur :8081
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:dev
    container_name: dev_onboard_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker,dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  ai-service:
    build:
      context: ./ai/ai-service
      dockerfile: Dockerfile
    container_name: dev_onboard_ai_service
    ports:
      - "8000:8000"
    networks:
      - backend
    restart: unless-stopped

volumes:
  pgdata: 
  grafana_data:

networks:
  backend:
    driver: bridge